# Generated by Django 5.0.8 on 2024-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, default='default_category', max_length=100)),
                ('limit', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
