# Generated by Django 5.0.8 on 2025-01-13 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_budget_options_remove_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2025, 12, 31)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2025, 1, 1)),
        ),
    ]
