# Generated by Django 5.0.8 on 2025-01-15 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_category_default_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.transactiongroup'),
        ),
    ]
