# Generated by Django 5.0.8 on 2025-01-15 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_budget_end_date_alter_budget_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 1, 31)),
        ),
    ]
