# Generated by Django 5.0.8 on 2025-02-20 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_image_remove_documentscans_invoice_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentScans',
            new_name='DocumentScan',
        ),
    ]
