# Generated by Django 5.0.8 on 2025-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_documentscans_documentscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='allocation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
