# Generated by Django 5.0.8 on 2025-02-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_budgetitem_allocation_alter_transaction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='category_id',
        ),
    ]
