# Generated by Django 5.0.8 on 2025-03-17 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_budgetitem_budget_unique_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 3, 31)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 3, 1)),
        ),
    ]
