# Generated by Django 5.0.8 on 2025-03-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_budget_end_date_alter_budget_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isIncomeType',
            field=models.BooleanField(default=False),
        ),
    ]
