# Generated by Django 5.0.8 on 2025-03-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_category_isincometype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='isIncomeType',
            new_name='is_income_type',
        ),
    ]
