# Generated by Django 5.0.8 on 2025-03-23 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_isincometype_category_is_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2025, 3, 31)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2025, 3, 1)),
        ),
    ]
