# Generated by Django 5.0.8 on 2025-03-25 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_budget_end_date_alter_budget_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#0062ff', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in #RRGGBB format', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
