# Generated by Django 5.0.8 on 2025-03-25 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#e74297bf', max_length=9, validators=[django.core.validators.RegexValidator(message='Color must be in #RRGGBB or #RRGGBBAA format', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')]),
        ),
    ]
