name: CI

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Run pre-commit hooks
      shell: devenv shell bash -- -e {0}
      run: |
        pre-commit run -a

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Run pre-commit hooks
      shell: devenv shell bash -- -e {0}
      run: |
        devenv up -d
        pytest
